[tool.poetry]
name = "optimization"
version = "0.1.0"
description = ""
authors = ["ElStabilini <el.stabilini@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
charset-normalizer = "^3.4.0"

quibocal = {git = "https://github.com/qiboteam/qibocal.git", branch = "qua"} 


[
tool.poetry.group.dev.dependencies
]
ipykernel = "^6.29.5"
jupyter_client = "^8.6.3"
pre-commit = "^3.8.0"
debugpy = "^1.8.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
